config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'
  get 'courses/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"
  
  resources :users
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum state: { invicto: 0, repitencia_1: 1, observado: 2 }
  validates :first_name, :last_name, :email, :password, presence: true
  validates :password, length: { minimum: 6 }
  validate :email_institucional

  private

  def email_institucional
    return if email.nil? || email.match(/^(.+)\.(.+)@unmsm.edu.pe$/)

    errors.add(:email, 'no pertenece a UNMSM')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])  
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = user.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])  
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<h1>Cursos</h1>
<%= link_to "Crear nuevo curso", new_course_path %>
<ul>
    <table style="width:100%">
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Ciclo</th>
        <th>Plan</th>
        <th>Credtitos</th>
      </tr>
      <% @courses.each do |course| %>
      <tr>
        <td><%= course.id %></td>
        <td><%= course.name %></td>
        <td><%= course.cicle %></td>
        <td><%= course.plan %></td>
        <td><%= course.credits %></td>
        <td><a href="/courses/<%= course.id %>">Ver</td>
        <td><a href="/courses/<%= course.id %>/edit">Editar</td>
        <td><%= link_to "Eliminar", course_path(course),
                  method: :delete,
                  data: { confirm: "¿Estás seguro?" } %></td>
      </tr>
      <% end %>
    </table> 
</ul>
<p>Find me in app/views/users/index.html.erb</p>

app/views/courses/new.html.erb
<h1>Nuevo Usuario</h1>
<%= form_with scope: :course, url: courses_path, local: true do |form| %>
<% if @course.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@course.errors.count, "error") %> errores evitan crear tu usuario:
    </h2>
    <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :cicle %><br>
    <%= form.text_field :cicle %>
  </div>
  <div>
    <%= form.label :plan %><br>
    <%= form.text_field :plan %>
  </div>
  <div>
    <%= form.label :credits %><br>
    <%= form.text_field :credits %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Regresar', courses_path %>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p>Diseñado por Joseph Vega</p>
</footer>

app/views/layouts/_nav.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <a class="h5 my-0 me-md-auto fw-normal" href="../">FII UNMSM</a>
  <nav class="my-2 my-md-0 me-md-3">
    <a class="p-2 text-dark" href="/users">Usuarios</a>
    <a class="p-2 text-dark" href="/courses">Cursos</a>
    <a class="p-2 text-dark" href="#">Solicitudes</a>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectFii</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/users/index.html.erb
<h1>Usuarios</h1>
<%= link_to "Crear nuevo usuario", new_user_path %>
<ul>
    <table style="width:100%">
      <tr>
        <th>ID</th>
        <th>Nombres</th>
        <th>Apellidos</th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><a href="/users/<%= user.id %>">Ver</td>
        <td><a href="/users/<%= user.id %>/edit">Editar</td>
        <td><%= link_to "Eliminar", user_path(user),
                  method: :delete,
                  data: { confirm: "¿Estás seguro?" } %></td>
      </tr>
      <% end %>
    </table> 
</ul>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>
<%= form_with scope: :user, url: users_path, local: true do |form| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %> errores evitan crear tu usuario:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Regresar', users_path %>

app/views/users/show.html.erb
<h1>Usuario #<%=@user.id%></h1>
<ul>
    <table style="width:100%">
      <tr>
        <th>Nombres</th>
        <th>Apellidos</th>
        <th>Email</th>
        <th>Estado</th>
        <th>¿Es admin?</th>
      </tr>
      <tr>
        <td><%= @user.first_name %></td>
        <td><%= @user.last_name %></td>
        <td><%= @user.email %></td>
        <td><%= @user.state %></td>
        <td><%= @user.admin %></td>
      </tr>
    </table> 
</ul>
<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to "Eliminar", user_path(@user),
                  method: :delete,
                  data: { confirm: "¿Estás seguro?" } %> | 
<%= link_to 'Regresar', users_path %>